import { DocumentType } from './photo-state.service';

export const DOCUMENT_TYPES: DocumentType[] = [
  { id: 'passport_eu', name: 'Passport/Schengen Visa (EU Standard)', widthMm: 35, heightMm: 45 },
  { id: 'visa_usa', name: 'USA Visa', widthMm: 51, heightMm: 51 },
  { id: 'passport_india', name: 'Indian Passport', widthMm: 51, heightMm: 51 },
  {
    id: 'legacy_lichnoe_delo',
    name: 'Legacy: Personal file photo',
    widthMm: 90,
    heightMm: 120,
    topOffsetMinMm: 5,
    topOffsetMaxMm: 5,
    headHeightMinMm: 60,
    headHeightMaxMm: 60,
    colorMode: 'color',
    paperType: 'glossy',
    description: 'Legacy format: 9x12 cm personal file photo.'
  },
  {
    id: 'legacy_students_license_bw',
    name: 'Legacy: Student ID black and white',
    widthMm: 30,
    heightMm: 40,
    topOffsetMinMm: 2,
    topOffsetMaxMm: 4,
    colorMode: 'bw',
    paperType: 'glossy',
    description: 'Legacy format: 3x4 cm black-and-white student ID photo.'
  },
  {
    id: 'legacy_razreshenie_na_rabotu_color',
    name: 'Legacy: Moscow work permit color',
    widthMm: 30,
    heightMm: 40,
    topOffsetMinMm: 2,
    topOffsetMaxMm: 2,
    headHeightMinMm: 20,
    headHeightMaxMm: 20,
    colorMode: 'color',
    paperType: 'glossy',
    description: 'Legacy format: 3x4 cm color work permit photo.'
  },
  {
    id: 'legacy_med_book_color',
    name: 'Legacy: Medical book color',
    widthMm: 30,
    heightMm: 40,
    topOffsetMinMm: 2,
    topOffsetMaxMm: 2,
    headHeightMinMm: 20,
    headHeightMaxMm: 20,
    colorMode: 'color',
    paperType: 'any',
    description: 'Legacy format: 3x4 cm medical book photo.'
  },
  {
    id: 'legacy_med_spravka',
    name: 'Legacy: Medical certificate',
    widthMm: 30,
    heightMm: 40,
    topOffsetMinMm: 2,
    topOffsetMaxMm: 2,
    headHeightMinMm: 20,
    headHeightMaxMm: 20,
    colorMode: 'color',
    paperType: 'any',
    description: 'Legacy format: 3x4 cm medical certificate photo.'
  },
  {
    id: 'legacy_registration_moscow',
    name: 'Legacy: Moscow temporary registration',
    widthMm: 30,
    heightMm: 40,
    topOffsetMinMm: 2,
    topOffsetMaxMm: 2,
    headHeightMinMm: 20,
    headHeightMaxMm: 20,
    colorMode: 'bw',
    paperType: 'any',
    description: 'Legacy format: 3x4 cm black-and-white registration photo.'
  },
  {
    id: 'legacy_gun_permit',
    name: 'Legacy: Gun permit',
    widthMm: 30,
    heightMm: 40,
    topOffsetMinMm: 2,
    topOffsetMaxMm: 2,
    headHeightMinMm: 20,
    headHeightMaxMm: 20,
    colorMode: 'bw',
    paperType: 'any',
    decoration: 'leftcorner',
    description: 'Legacy format: 3x4 cm black-and-white permit photo with optional corner.'
  },
  {
    id: 'legacy_drivers_licence',
    name: 'Legacy: Driver license',
    widthMm: 30,
    heightMm: 40,
    topOffsetMinMm: 2,
    topOffsetMaxMm: 2,
    headHeightMinMm: 30,
    headHeightMaxMm: 30,
    colorMode: 'color',
    paperType: 'any',
    backgroundColor: '#ec5f1d',
    description: 'Legacy format: 3x4 cm driver license photo with red background.'
  },
  {
    id: 'legacy_voen_bilet',
    name: 'Legacy: Military ID',
    widthMm: 30,
    heightMm: 40,
    topOffsetMinMm: 2,
    topOffsetMaxMm: 2,
    headHeightMinMm: 18,
    headHeightMaxMm: 18,
    colorMode: 'bw',
    paperType: 'any',
    decoration: 'rightcorner',
    description: 'Legacy format: 3x4 cm black-and-white military ID photo with right corner.'
  },
  {
    id: 'legacy_zagranpass_mid',
    name: 'Legacy: Russian international passport MID',
    widthMm: 36,
    heightMm: 47,
    topOffsetMinMm: 2,
    topOffsetMaxMm: 2,
    headHeightMinMm: 25,
    headHeightMaxMm: 35,
    colorMode: 'color',
    paperType: 'any',
    description: 'Legacy format: 36x47 mm Russian international passport photo.'
  },
  {
    id: 'legacy_zagran_pass_ovir',
    name: 'Legacy: Russian international passport OVIR',
    widthMm: 35,
    heightMm: 45,
    topOffsetMinMm: 2,
    topOffsetMaxMm: 2,
    headHeightMinMm: 25,
    headHeightMaxMm: 35,
    colorMode: 'color',
    paperType: 'matte',
    description: 'Legacy format: 35x45 mm Russian international passport photo.'
  },
  {
    id: 'legacy_passport_rf',
    name: 'Legacy: Russian passport',
    widthMm: 35,
    heightMm: 45,
    topOffsetMinMm: 2,
    topOffsetMaxMm: 5,
    headHeightMinMm: 35,
    headHeightMaxMm: 36,
    headWidthMinMm: 18,
    headWidthMaxMm: 25,
    colorMode: 'color',
    paperType: 'any',
    description: 'Legacy format: 35x45 mm Russian passport photo.'
  },
  {
    id: 'legacy_passport_old',
    name: 'Legacy: Russian passport old format',
    widthMm: 37,
    heightMm: 47,
    topOffsetMinMm: 4,
    topOffsetMaxMm: 6,
    eyesLineMinMm: 11,
    eyesLineMaxMm: 13,
    colorMode: 'color',
    paperType: 'any',
    description: 'Legacy format: 37x47 mm old Russian passport photo.'
  },
  {
    id: 'legacy_schengen_belgium',
    name: 'Legacy: Schengen visa Belgium',
    widthMm: 35,
    heightMm: 45,
    topOffsetMinMm: 2,
    topOffsetMaxMm: 2,
    headHeightMinMm: 32,
    headHeightMaxMm: 36,
    eyesLineMinMm: 13,
    eyesLineMaxMm: 13,
    colorMode: 'color',
    paperType: 'any',
    description: 'Legacy format: 35x45 mm Schengen visa photo.'
  },
  {
    id: 'legacy_schengen_hungary',
    name: 'Legacy: Schengen visa Hungary',
    widthMm: 35,
    heightMm: 45,
    topOffsetMinMm: 2,
    topOffsetMaxMm: 2,
    headHeightMinMm: 32,
    headHeightMaxMm: 36,
    eyesLineMinMm: 13,
    eyesLineMaxMm: 13,
    colorMode: 'color',
    paperType: 'any',
    description: 'Legacy format: 35x45 mm Schengen visa photo.'
  }
];
